name: helloGitHubAction

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 파이썬 실행!!
      run: python test.py

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run main.py
      working-directory: dataAnalysis/macro
      run: python main.py
